#!/bin/bash

IDL_FILE="test.idl"

usage()
{
    echo
    echo "USAGE: $0 test_folder]"
    echo "Params List";
    echo "    test_folder  : folder where files for the test are located" 
    echo "    --help or -h : Show this info"
    echo
}

if [ -z $1 ]; then
    echo "ERROR: Parameters expected"
    usage
    exit
fi

if [ $1 == "--help" ] || [ $1 == "-h" ]; then
    usage
    exit
fi

HOME_PATH=`pwd`
#echo $HOME_PATH
WORK_PATH=$HOME_PATH/$1
#echo $WORK_PATH

if [ ! -d $WORK_PATH ]; then
    echo "ERROR: Not found directory: " $WORK_PATH
    usage
    exit
fi

cd $WORK_PATH
NUMBER_SUBFOLDERS=`ls -d */ | wc -l`
echo $NUMBER_SUBFOLDERS
#echo "${IDL_PATH[0]}"
#echo "${IDL_PATH[1]}"

if [ "$NUMBER_SUBFOLDERS" -gt 1 ]; then
    echo "ERROR: In folder " $WORK_PATH " there are more of one sub-folders"
    exit
fi

if [ "$NUMBER_SUBFOLDERS" -eq 1 ]; then
    IDL_FOLDER=`ls -d */`
    echo "Deleting files in folder $WORK_PATH/$IDL_FOLDER"
    rm -rf $WORK_PATH/$IDL_FOLDER/*
fi

echo "Generating python file from IDL file" $IDL_FILE

/usr/local/lib/cyclonedds/bin/idlc -l/usr/local/lib/python3.8/dist-packages/cyclonedds/_idlpy.cpython-38-x86_64-linux-gnu.so -Wno-implicit-extensibility -o ${WORK_PATH} ${WORK_PATH}/$IDL_FILE

name=$(echo "test.idl" | cut -f 1 -d '.')
IDL_FOLDER=`ls -d */`
IDL_FILE_GENERATED=$WORK_PATH/$IDL_FOLDER"_"
IDL_FILE_GENERATED=$IDL_FILE_GENERATED$(echo $IDL_FILE | cut -f 1 -d '.')
IDL_FILE_GENERATED=$IDL_FILE_GENERATED".py"
#echo $IDL_FILE_GENERATED

if [ ! -f $IDL_FILE_GENERATED ]; then
    echo "ERROR: Python file ${IDL_FILE_GENERATED} has not been autogenerated"
    exit
fi

echo "Python file ${IDL_FILE_GENERATED} has been autogenerated"

echo "Launching publisher during 10 seconds"
python3 publisher.py &

echo "Launching subscriber during 10 seconds"
python3 subscriber.py &

sleep 10

killall python3
