// module parent {
//     module child {
//         struct struct_test {
//             char var;
//         };
//     };
// };

module in {
   module is {
       struct struct_test {
           char var;
       };
   };
};

