module module_test {
    union assert switch (int8) {
            case 1:
                int16 value_int;
            case 2:
                char value_char_array[5];
            default:
                string value_string;
    };
    struct struct_test {
        assert union_field;
    };
};

