"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: module_test
  IDL file: test.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import module_test


@dataclass
@annotate.final
@annotate.autoid("sequential")
class struct_test(idl.IdlStruct, typename="module_test.struct_test"):
    var: types.char


