module module_test {
    bitmask import {
        value1,
        value2
    };
    struct struct_test {
        import bitmask_value;
    };
};


// module module_test {
//     bitmask except {
//         finally,
//         for
//     };
//     struct struct_test {
//         for from;
//     };
// };

